mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.caihua.bean
server:
  port: 8989
 # servlet:
   # session:
    #  timeout: 1m
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//127.0.0.1:1521/XE
    username: system
    password: hua1996cai






